apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-website-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-website
  template:
    metadata:
      labels:
        app: simple-website
    spec:
      containers:
      - name: simple-website-container
        image: gcr.io/YOUR_PROJECT_ID/my-image
        ports:
        - containerPort: 3000
