name: Build, Push, and Deploy to GKE

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Authenticate to Google Cloud
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}  # Your GCP service account JSON key

    # Step 3: Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    # Step 4: Install gke-gcloud-auth-plugin
    - name: Install gke-gcloud-auth-plugin
      run: |
        curl -sSL https://sdk.cloud.google.com | bash
        source $HOME/google-cloud-sdk/path.bash.inc
        gcloud components install gke-gcloud-auth-plugin --quiet

    # Step 5: Verify gke-gcloud-auth-plugin
    - name: Verify gke-gcloud-auth-plugin
      run: |
        gke-gcloud-auth-plugin --version

    # Step 6: Get GKE credentials
    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials simple-website-cluster --zone europe-west2-b --project ${{ secrets.GCP_PROJECT_ID }}

    # Step 7: Set Kubernetes context
    - name: Set Kubernetes context
      run: |
        kubectl config use-context gke_${{ secrets.GCP_PROJECT_ID }}_${{ secrets.GCP_ZONE }}_${{ secrets.GKE_CLUSTER_NAME }}

    # Step 8: Build Docker image
    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/simple-website:${{ github.sha }} .

    # Step 9: Push Docker image to GCR
    - name: Push Docker image to GCR
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/simple-website:${{ github.sha }}

    # Step 10: Deploy to GKE
    - name: Deploy to GKE
      run: |
        kubectl set image deployment/simple-website-deployment simple-website-container=gcr.io/${{ secrets.GCP_PROJECT_ID }}/simple-website:${{ github.sha }}
        kubectl apply -f k8s-deployment.yaml
        kubectl apply -f k8s-service.yaml
