
name: Build, Push, and Deploy to GKE

on:
  push:
    branches:
      - main  # or specify the branch to trigger the workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Authenticate to Google Cloud
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}  # Service account JSON key stored as GitHub Secret

    # Step 3: Set up Google Cloud SDK for gcloud and kubectl
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    # Step 4: Configure Docker to use gcloud as a credential helper
    - name: Configure Docker for Google Cloud
      run: |
        gcloud auth configure-docker --quiet

    # Step 5: Build Docker image
    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-image:${{ github.sha }} .

    # Step 6: Push Docker image to GCR
    - name: Push Docker image to GCR
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-image:${{ github.sha }}

    # Step 7: Set up kubectl with GKE cluster context
    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials simple-website-cluster --zone europe-west2-b --project ${{ secrets.GCP_PROJECT_ID }}

    # Step 8: Deploy to GKE
    - name: Deploy to GKE
      run: |
        kubectl set image deployment/simple-website-deployment simple-website-container=gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-image:${{ github.sha }}
