name: Build and Push Docker Image to GCR

on:
  push:
    branches:
      - main  # or specify the branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}  # Your GCP service account JSON key stored as GitHub Secret

    - name: Configure Docker for Google Cloud
      run: |
        gcloud auth configure-docker --quiet  # This sets up Docker to use your Google Cloud credentials

    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-image:${{ github.sha }} .

    - name: Push Docker image to GCR
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-image:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Make sure build job runs before deploy

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set up kubectl
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to GKE
      run: |
        gcloud container clusters get-credentials simple-website-cluster --zone europe-west2-b --project ${{ secrets.GCP_PROJECT_ID }}
        kubectl apply -f kubernetes/deployment.yaml
        kubectl apply -f kubernetes/service.yaml
        kubectl rollout restart deployment/simple-website-deployment